source :rubygems
gem 'guard'
gem 'puppet-lint'
gem 'puppet'
gem 'guard-shell', '>= 0.4.0'
gem 'libnotify' if RUBY_PLATFORM.downcase.include?("linux")
gem 'growl' if RUBY_PLATFORM.downcase.include?("darwin")
gem 'terminal-notifier-guard'
